version: '3.4'

services:
  goiabinha-api-database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pa55w0rd#2022
      - ACCEPT_EULA=Y  
    ports:
      - 1433:1433
  goiabinha-api-app:
    container_name: goiabinha-app
    build:
      context: .
      dockerfile: .
    ports:
     - 8090:80     
    depends_on:
     - goiabinha-api-database
    environment:
      - DB_SERVER= goiabinha-api-database
      - DB_PORT=1433
      - DB_SA_PASSWORD= Pa55w0rd#2022
      - DB_NAME= UsersAPI